blackout:
  lidar: true
  rate: 0.2

model:
  fuser:
    type: ConvFuser
    in_channels: [80, 256]
    out_channels: 256

lr_config:
  policy: cyclic
  target_ratio: 5.0
  cyclic_times: 1
  step_ratio_up: 0.4

momentum_config:
  policy: cyclic
  cyclic_times: 1
  step_ratio_up: 0.4

max_epochs: 20

optimizer:
  lr: 0.5e-4

gt_paste_stop_epoch: -1

data:
  samples_per_gpu: 8
  workers_per_gpu: 8