lr_config:
  policy: cyclic
  target_ratio: 5.0
  cyclic_times: 1
  step_ratio_up: 0.4

momentum_config:
  policy: cyclic
  cyclic_times: 1
  step_ratio_up: 0.4

optimizer:
  lr: 1.0e-4

gt_paste_stop_epoch: 15

data:
  samples_per_gpu: 16
  workers_per_gpu: 8
