# Fusion model without checkpoint
# all configs in this folder make use of both pretrained camera and LiDAR weights.
# as the LiDAR checkpoint is loaded last, overlapping weights (i.e. the decoder and head) are loaded from the LiDAR checkpoint

load_from: ["data/pretrained/camera-only-det.pth", "data/runs/centerhead_lidar_baseline/run-e50d2cdf-a07c0f6a/epoch_20.pth"]
lr_config:
  policy: CosineAnnealing
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 0.33333333
  min_lr_ratio: 1.0e-3
