# Fusion model with lidar checkpoint

load_from: data/runs/centerhead_lidar_baseline/run-e50d2cdf-a07c0f6a/epoch_20.pth

lr_config:
  policy: CosineAnnealing
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 0.33333333
  min_lr_ratio: 1.0e-3