map_resolution_x: [-50.0, 50.0, 200]
map_resolution_y: [-50.0, 50.0, 200]

model:
  encoders:
    map:
      encoder:
        type: conv
        channels: [12,18,24,32]
  fuser:
    type: ConvFuser
    in_channels: [32]
    out_channels: 256
  decoder:
    backbone:
      type: SECOND
      in_channels: 256
      out_channels: [128, 256]
      layer_nums: [5, 5]
      layer_strides: [1, 2]
      norm_cfg:
        type: BN
        eps: 1.0e-3
        momentum: 0.01
      conv_cfg:
        type: Conv2d
        bias: false
    neck:
      type: SECONDFPN
      in_channels: [128, 256]
      out_channels: [256, 256]
      upsample_strides: [1, 2]
      norm_cfg:
        type: BN
        eps: 1.0e-3
        momentum: 0.01
      upsample_cfg:
        type: deconv
        bias: false
      use_conv_for_no_stride: true
  heads:
    map:
      in_channels: 512

optimizer:
  type: AdamW
  lr: 1.0e-4
  weight_decay: 0.01
# optimizer:
#   type: AdamW
#   lr: 1.0e-4
#   weight_decay: 0.01
#   paramwise_cfg:
#     custom_keys:
#       absolute_pos_embed:
#         decay_mult: 0
#       relative_position_bias_table:
#         decay_mult: 0

optimizer_config:
  grad_clip:
    max_norm: 35
    norm_type: 2

lr_config:
  policy: step
  by_epoch: false
  step: 500
  gamma: 0.8
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 0.33333333
# lr_config:
#   policy: cyclic

momentum_config:
  policy: cyclic
