model:
  encoders:
    camera:
      vtransform:
        xbound: [-54.0, 54.0, 0.3]
        ybound: [-54.0, 54.0, 0.3]
  heads:
    object:
      train_cfg:
        grid_size: [1440, 1440, 41]

voxel_size: [0.075, 0.075, 0.2]
point_cloud_range: [-54.0, -54.0, -5.0, 54.0, 54.0, 3.0]
