# NOT part of the thesis models
# uses prior frame for temporal camera data (like BEVDet4d)

use_camera_4d: true
multi_adj_frame_id_cfg: [1, 2, 1] # number of frames used = multi_adj_frame_id_cfg[1] - multi_adj_frame_id_cfg[0]

model:
  merge_bev_4d_cfg: 
    type: concat
  loss_depth_weight: 3.0
  decoder:
    backbone:
      in_channels: 160
  encoders:
    camera:
      vtransform:
        type: BEVDepthLSSTransform


optimizer:
  lr: 0.75e-4
data:
  samples_per_gpu: 9