# NOT part of the thesis models
# reduced camera point cloud resolution at higher distance (for lower memory usage)

depth_bound: [1.0, 60.0, 1.5]
model:
  encoders:
    camera:
      vtransform:
        dbound: ${depth_bound}
        depth_decay: true

# for single gpu
data:
  samples_per_gpu: 24 
  workers_per_gpu: 8

# for 2x gpu
optimizer:
  lr: 2.0e-4
